version: '3'

services:
  web:
    build: .
    command: >
      sh -c "sleep 20 &&
              python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "django_new"
      MYSQL_USER: "yavuz"
      MYSQL_PASSWORD: "yavuz"
      MYSQL_ROOT_PASSWORD: "root"

